// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwqedddxumbgfgrcbtae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3cWVkZGR4dW1iZ2ZncmNidGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTM0NTksImV4cCI6MjA2NzEyOTQ1OX0.9tDbV8FK7ZgbSdCRVN8XW8PVKQfJe8jnc27mqgMTJ_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});